language: node_js
env:
  global:
    - TEST_LOC="sauce"
    - GOOGLE_CLIENT_ID=""
    - GOOGLE_CLIENT_SECRET=""
    - GOOGLE_API_KEY=""
    - REDISCLOUD_URL=""
    - BASE_URL=http://localhost:5000
    - SESSION_SECRET=not-so-secret-for-testing
    - USE_STANDALONE_PYRET=true
    - PYRET_RELEASE_BASE="/js"
    - CURRENT_PYRET_RELEASE=""
    - PORT=5000
    - SAUCE_TEST_TARGET="http://localhost:5000"
    - SAUCE_USERNAME="gibbs"
    - secure: "ggepdfVeVbbgu/KTtuIHOX4PgGjGSK3ClP6yJBlPm5DTFxc36MddW2aiKxgGOM51wyj28xie+8NRCM2VeYg1MHawfqDN4hlleqYRRAvpGnEekh+8xGLCFNs7IlICfjKtGZWiEQb4V88EAP8KKFnU7ZuMspvdX5z9cnTTPheTLC0hnslzCXP8/EGo4fB865b0N6s5XvZfVxxLHlfQzaZr4hgN9po8kLsPf0cN82A5BLbVuE51D2cbZw7vDEAD5jdEvb3mR3dBx9lJzpFfaP4R9qHESr3vjuhwpX9/vgwY4soEjCDTicF2/R9tvfGSp5KNw0DWr6sMTo3i2j16amem/TM4faMIHBxi9dGmZpw81DVbSElJw40HeKlE8qtlJZPGxeCCQt1THt0nRLCtFmBPJgjMN0snCQilB5V7AOVtBR6rU5OFJfbAqzHb92wEXSU1Q4LoPNa2EMUdT40hJHHUnDA+5zEao5B0pl4rjK2yr4Mm/3jrSwJZyDkgEe+r2TfVvSX1SjqAvHZBejdWhuqOPvewjoKZFwEd/6ucfackIoFj9H/EqSlmaHJzwfk3yZoYH/cRKLrRCXJV/5R+pvKHgM8V9W1ea8wsVF+EIAAet3jfoxXJw+5lDNQq8uDM93EqWtuO9N08WjmOZOm5BznSoYTa9loC/rNQGWNRwle7qJs="
  matrix:
    - SAUCE_BROWSER="chrome"
    - SAUCE_BROWSER="firefox"
node_js:
- 0.10.26
install:
- npm install
before_script:
- node src/run.js &
- sleep 3
script:
- mocha --timeout 120000
addons:
  sauce_connect: true
