language: node_js
env:
- GOOGLE_CLIENT_ID=""
- GOOGLE_CLIENT_SECRET=""
- GOOGLE_API_KEY=""
- REDISCLOUD_URL=""
- BASE_URL=http://localhost:5000
- SESSION_SECRET=not-so-secret-for-testing
- USE_STANDALONE_PYRET=true
- PYRET_RELEASE_BASE="/js"
- CURRENT_PYRET_RELEASE=""
- PORT=5000
node_js:
- 0.10.26
install:
- npm install
script:
- make selenium-test-local
