language: node_js
env:
  global:
    - TEST_LOC="sauce"
    - GOOGLE_CLIENT_ID=""
    - GOOGLE_CLIENT_SECRET=""
    - GOOGLE_API_KEY=""
    - REDISCLOUD_URL=""
    - BASE_URL=http://localhost:5000
    - SESSION_SECRET=not-so-secret-for-testing
    - USE_STANDALONE_PYRET=true
    - PYRET_RELEASE_BASE="https://s3.amazonaws.com/pyret-horizon/current"
    - PYRET="https://s3.amazonaws.com/pyret-horizon/new-horizons/cpo-main.jarr"
    - CURRENT_PYRET_RELEASE=""
    - PORT=5000
    - SAUCE_TEST_TARGET="http://localhost:5000"
    - SAUCE_USERNAME="pyret-lang"
    - secure: "e0vpQGmW0d69Ql72Mw6gsGsMxAKgt61ZNqsfQEtNlAGtx7CbTKe3xg8kF1ygwFVEB7GDmTaojTcSGbRwqqZ5GAa8dsTAkefhOtfCDV5KUjvXXbpo9J/8YLiZiIy7ksHyh1yhByvvWmZZpjmdxWwcH8gUqtpae3bGtz7rQX3jLf2v3OR5uVFt8vKRMSR9imCWmq6tpnu+GVoaCFOHjq3U7LS1h78R2LJz+MnTuCbDtYFlxp/sAyS7vSXssFScl6wqOsgH5PHlj+kaHhFWLhzsAzG1RoHftqqIeinXzDcYo8EC/c6O3hMf2KtHm/Hsh1dPR8GnE6WClxPw0xNbh10jVf7b1CXuzKGF8a1JlmtsVztiujsMswZGGLpTkqBvBAiuDsMOwKFNk7UrR5FA/0bVMMsluKxW/0UBzVPN9QyMKAs19ca1t/qT3abxYFyvXrDibKMLuS1uCCsZbwTkjkPwfWBzin8ohK2gLi+y24eQFSd27XWcmk+fJHfgJ458OgvczubK0CsyPAaJtCvRBYKvLQaEtkc4RkoM0yx6NhYYLCZqH1DRneam40rVSrVO41yT/PUnA5U64q16ptbn90Vgw/yKlp9OLtWKheBDTinwbst1kegbCSj4qZtORFLIQIUsZQN6SUm9tCACqFosDpRXAzURc2IOdsSUmtJEqvkijsc="
  matrix:
    - SAUCE_BROWSER="chrome"
node_js:
- 4.3.1
install:
- npm install --ignore-scripts
- make web
#- make build/web/js/cpo-main.jarr
#before_script:
#- node src/run.js &
#- sleep 3
#script:
#- mocha --harmony
script:
- echo "skipping tests"
#addons:
#  sauce_connect: true
deploy:
  provider: s3
  access_key_id: AKIAIFY44WM3LGA4OQSQ
  secret_access_key:
    secure: "kqqBFy3k5Dpz2KXsXHSjdrCiONabMNvWPv/GMhnqEMB4GFlO9QitztlprL/UE4mEX+SRlkSCwBErqRvQkSXobgTrGDpY8nGGYtTf8491rloUyj3sfBmnkzUhWFJUhz6luC1yoik+pC1aP27s5tm8x3A09ddU0eqiDUUet2QxzVsHxgfqENUdjvUL+75ieABf/tVs1tK/RSMbbZ7kqA4SOkdyv0135V6m+LlvjWB3RKHTHRhxOmA4BN+0zSagOyhhQAVsFdBikzK+uzjjdFknYo4Fmubz/epV+ZIYbbxKtAA23A6iKZtyVVplgxdQ9zU+5+MS6wCIRAribUxf18zKSGLQ7HAUxCrbGu42bxHIIbJez4yUKMFFChah5L7wj8FnZh9+HwHlaVVLSWqBfqtK676fXQB5nowXYufFEZlfIneLTBQWppOq89eWBoVYNy3iMNtWWuZkygsXTQG8a/BDE1tzm5CGax0SHtxEoBt5suxgDM/I46wKY8cL9+R+VQSx52GM+lEELBGpqRVvAvzhvoo8o7Q5semqFLhpdj81OT2vOxq928JY+onMQkYs/8TR/VyGEzJp0wyar5S2xgcoLfC47vaK0UsWqt/uQun9KVYwsr49gC7WQHjmYmbH+TW8QdiQP/FzD4mLOUXAxS/MZKlEMz9mXL5YgbtjoZKmkkU"
  bucket: 'pyret-horizon'
  local-dir: build/web/js
  upload-dir: new-horizons
  acl: public_read
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: brownplt/code.pyret.org
    branch: new-horizons
