language: node_js
env:
  global:
    - TEST_LOC="sauce"
    - GOOGLE_CLIENT_ID=""
    - GOOGLE_CLIENT_SECRET=""
    - GOOGLE_API_KEY=""
    - REDISCLOUD_URL=""
    - BASE_URL=http://localhost:5000
    - SESSION_SECRET=not-so-secret-for-testing
    - USE_STANDALONE_PYRET=true
    - PYRET_RELEASE_BASE="https://s3.amazonaws.com/pyret-horizon/current"
    - PYRET="https://s3.amazonaws.com/pyret-horizon/new-horizons/cpo-main.jarr"
    - CURRENT_PYRET_RELEASE=""
    - PORT=5000
    - SAUCE_TEST_TARGET="http://localhost:5000"
    - SAUCE_USERNAME="pyret-lang"
    - secure: "e0vpQGmW0d69Ql72Mw6gsGsMxAKgt61ZNqsfQEtNlAGtx7CbTKe3xg8kF1ygwFVEB7GDmTaojTcSGbRwqqZ5GAa8dsTAkefhOtfCDV5KUjvXXbpo9J/8YLiZiIy7ksHyh1yhByvvWmZZpjmdxWwcH8gUqtpae3bGtz7rQX3jLf2v3OR5uVFt8vKRMSR9imCWmq6tpnu+GVoaCFOHjq3U7LS1h78R2LJz+MnTuCbDtYFlxp/sAyS7vSXssFScl6wqOsgH5PHlj+kaHhFWLhzsAzG1RoHftqqIeinXzDcYo8EC/c6O3hMf2KtHm/Hsh1dPR8GnE6WClxPw0xNbh10jVf7b1CXuzKGF8a1JlmtsVztiujsMswZGGLpTkqBvBAiuDsMOwKFNk7UrR5FA/0bVMMsluKxW/0UBzVPN9QyMKAs19ca1t/qT3abxYFyvXrDibKMLuS1uCCsZbwTkjkPwfWBzin8ohK2gLi+y24eQFSd27XWcmk+fJHfgJ458OgvczubK0CsyPAaJtCvRBYKvLQaEtkc4RkoM0yx6NhYYLCZqH1DRneam40rVSrVO41yT/PUnA5U64q16ptbn90Vgw/yKlp9OLtWKheBDTinwbst1kegbCSj4qZtORFLIQIUsZQN6SUm9tCACqFosDpRXAzURc2IOdsSUmtJEqvkijsc="
  matrix:
    - SAUCE_BROWSER="chrome"
node_js:
- 4.3.1
install:
- npm install --ignore-scripts
- make web
- make build/web/js/cpo-main.jarr
before_script:
- node src/run.js &
- sleep 3
#script:
#- mocha --harmony
addons:
  sauce_connect: true
deploy:
  provider: s3
  access_key_id: AKIAIFY44WM3LGA4OQSQ
  secret_access_key:
    secure: "d99Tlr8DCIauEBzMi7Z+wymF7QqkZU1jkmIpWVTaxM1/fCrNFdWdTzS+7pFMw2uP/dTsyoJo9/hldNTWH1mhD9ao/qr1fhf6FwR0kKCZiDeTZ52vP1wMKUNRijR3jj8CSpWehFF2cvI+sr0ayULkF1RXGRvhvTb6w+jfAD/N9XQyUOYkJX/TGR448L2dbh3oEwDcmEMKt7UxZFC6HUQ7wDyw2yQKLacioeZ+cdBdsR8YU2QkziWDiwfUs+0RQcSWj7Tto94DdLWBJlhhep9WMuKNZZp0qFjXg8A0yGav8cBeLqpizXQLIxSGlqe4AipO1HTEEPxPWeVL+7yDv5373+sIRvysKTX8ZaJreLA5JKk53k8tE9xHuDF6Ct2fNiZBOfz+7iKvr+x1ubCnBAiEPqLlj5V5s/LMoKz1Rq/gJSuUjWBN28pQHYZxi9+pvtvSHPkSvT51IE8Kj7TOKuKxAbPhi8s+9f+uT1NvQBrZOsyvkhbXewuq3+DeU9DdFkZd6pI2lg+7wRrnxHuDp7gDBUPpthW+2+5jyQ+LbLWsLtnS76GLwM6XHOT/IGcF56A4HDNfbp9O7vLwocqZSKEVo1uCnPAfvV+18PeThcCeHvUFru93bqEJ9pGAuU4W2IOaBshL7WG5m7FdySlbZQHkxidALJcmCfdHy50j94l8sNo="
  bucket: 'pyret-horizon'
  local-dir: build/web/js
  upload-dir: new-horizons
  acl: public_read
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: brownplt/code.pyret.org
    branch: new-horizons
